DELIMITER $$

CREATE TRIGGER `DCBE`.`t_CUSTOMERS_AFTER_INSERT` AFTER INSERT ON `t_CUSTOMERS` FOR EACH ROW
BEGIN
	IF 	(	( NEW.Legal_Id = NULL AND NEW.Natural_Id = NULL )
			OR	( NEW.Legal_Id <> NULL AND NEW.Natural_Id <> NULL)
		)
	THEN
        SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'SDFSDFS';
	END IF;
END;

$$